# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JqMyg6WmGarxsKsoRuTUK7OL9nSa5MNg
"""

import cv2
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

from google.colab.patches import cv2_imshow

img = cv2.imread("/content/drive/MyDrive/flower.jpg")
cv2_imshow(img)

plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))



plt.show()

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Display using matplotlib with grayscale colormap
plt.imshow(gray, cmap='gray')
plt.axis('off')  # optional, hides axis
plt.show()

_, binary = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY)
plt.imshow(binary, cmap="gray")
plt.title("Binary Image")
plt.axis("off")
plt.show()

plt.figure(figsize=(10,4))
plt.subplot(1,3,1)
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.title("RGB Image")
plt.axis("off")

plt.subplot(1,3,2)
plt.imshow(gray, cmap="gray")
plt.title("Grayscale")
plt.axis("off")

plt.subplot(1,3,3)
plt.imshow(binary, cmap="gray")
plt.title("Binary")
plt.axis("off")

plt.show()